import os
import numpy as np
import pandas as pd
from tqdm import tqdm
from clip_model import encode_image

"""
Purpose:
 - Load metadata CSV
    - For each image, generate CLIP embedding and store it in a list
 
 - Save the list of embeddings as a .npy file. 
   This will be used for fast retrieval during search.
 
 - Save the metadata (including image paths and product info) 
   in a new CSV for reference during search results display.

===================================================================================

Values:
  1. Embeddings: List[] --> List to hold CLIP embeddings. CLIP embeddings consist of vectors 
                             that represent the visual features of the images. These vectors 
                             are generated by the CLIP model and are used for similarity comparisons 
                             during search. Each embedding is a high-dimensional vector that captures 
                             the visual characteristics of the corresponding image, allowing us to 
                             compare and retrieve similar items based on their visual features.
    
    2. Metadata: CSV     --> A structured file that contains information about each product, 
                              such as brand, product ID, price, currency, category, and URL.
    
    3. rows: List[Dict]  --> A list of dictionaries where each dictionary contains the metadata
                             for a single product. This metadata will be saved in a new CSV file 
                             and will be used to display relevant information about the products 
                             when search results are retrieved based on the CLIP embeddings.                       
"""

# Load metadata CSV
metadata = pd.read_csv("data/metadata.csv")

embeddings = [] 
rows = []

for _, row in tqdm(metadata.iterrows(), total=len(metadata)):
    image_path = row['image_path']
    image_embedding = encode_image(image_path)
    embeddings.append(image_embedding.flatten())
    
    image_information = {
        "image_path": image_path,
        "brand": row['brand'],
        "product_id": row['product_id'],
        "price": row['price'],
        "currency": row['currency'],
        "category": row['category'],
        "url": row["product_url"]
        }
    rows.append(image_information)

# Save embeddings and metadata
embeddings_array = np.array(embeddings)
np.save("data/embeddings.npy", embeddings_array)

metadata_df = pd.DataFrame(rows)
metadata_df.to_csv("data/metadata_with_embeddings.csv", index=False)