import os
import numpy as np
import pandas as pd
from tqdm import tqdm
from clip_model import embed_image

"""
Purpose:
 - Load metadata CSV
    - For each image, generate CLIP embedding and store it in a list
 
 - Save the list of embeddings as a .npy file. 
   This will be used for fast retrieval during search.
 
 - Save the metadata (including image paths and product info) 
   in a new CSV for reference during search results display.

===================================================================================

Values:
  1. Embeddings: List[] --> List to hold CLIP embeddings. CLIP embeddings consist of vectors 
                             that represent the visual features of the images. These vectors 
                             are generated by the CLIP model and are used for similarity comparisons 
                             during search. Each embedding is a high-dimensional vector that captures 
                             the visual characteristics of the corresponding image, allowing us to 
                             compare and retrieve similar items based on their visual features.
    
    2. Metadata: CSV     --> A structured file that contains information about each product, 
                              such as brand, product ID, price, currency, category, and URL.                   
"""

# Load metadata CSV and define headers
metadata = pd.read_csv("data/metadata.csv")

# Image path setup --> Each path follows the same structure: data/images/{brand}/{image_id}_{brand}_{product_id}_{variant_id}.jpg
base_image_path = "data\\images\\"

embeddings = []


for _, row in tqdm(metadata.iterrows(), total=len(metadata)):
    image_id, product_id, variant_id, brand = row['image_id'], row['product_id'], row['variant_id'], row['brand']
        
    filename = f"{image_id}_{product_id}_{variant_id}.jpg"
    image_path = os.path.join(base_image_path, brand, filename)
    
    image_embedding = embed_image(image_path)
    embeddings.append(image_embedding.flatten())

# Save embeddings and metadata
embeddings_array = np.array(embeddings)
np.save("data/embeddings.npy", embeddings_array)